server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-authuser-v2
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://bgjagonl:ql47akVJC7vNPUfgOjmnaEAFWy4cghdn@moose.rmq.cloudamqp.com/bgjagonl


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent


resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstanceDiego:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        slidingWindowType: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80
  retry:
    instances:
      retryInstance:
        maxAttempts: 3
        waitDuration: 5s
      